use Factor base class
Humi-HR/taxman pull request #89
Opened 2023-09-01 16:01 UTC by mark-h-humi

follow-up to https://github.com/Humi-HR/taxman/pull/75/files#discussion_r1307915904

#75 introduced a base class for tax factors; let's use it whereever we can

2023-09-01 16:09 UTC, claus-humi requested changes

2023-09-01 16:09 UTC, claus-humi commented on lib/taxman/taxman2023/t3.rb
>        @tc_offset = tc_offset&.to_d
Should be default 0 if not set.

2023-09-01 16:09 UTC, claus-humi commented on lib/taxman/taxman2023/t4_generic.rb
> -      @tcp_offset = tcp_offset.to_d # Offset to personal exemption from provincial TD1, or we use the basic exemption
Should default to 0

2023-09-01 16:09 UTC, claus-humi commented on lib/taxman/taxman2023/factor.rb
> +        value = value.to_d unless value.is_a?(String)
How does `nil.to_d` work?

2023-09-01 16:15 UTC, mark-h-humi commented on lib/taxman/taxman2023/factor.rb
> +        value = value.to_d unless value.is_a?(String)
it's BigDecimal 0

2023-09-01 16:17 UTC, mark-h-humi commented on lib/taxman/taxman2023/t4_generic.rb
> -      @tcp_offset = tcp_offset.to_d # Offset to personal exemption from provincial TD1, or we use the basic exemption
yes that will happen in `super`; i did not change the logic

2023-09-01 16:18 UTC, mark-h-humi commented on lib/taxman/taxman2023/t3.rb
>        @tc_offset = tc_offset&.to_d
as this is a refactor i did change any logic

2023-09-01 16:20 UTC, mark-h-humi commented on lib/taxman/taxman2023/t3.rb
>        @tc_offset = tc_offset&.to_d
so basically the subclasses still have initializers only if they do something different that `Factor#initialize`

2023-09-05 14:19 UTC, claus-humi approved these changes
Looks more consistent now.

It's a weird part of the codebase and I hope that we starting 2024 won't have to deal with all these `nil` values as there should be actual inputs into these fields.

2023-09-05 15:02 UTC, merged